name: 'CodePipeline status'
description: 'Provide the status of CodePipeline'
author: 'Leonardo R.'
inputs:
  milliseconds: # change this
    required: false
    description: 'sample input: miliseconds'
    default: '2000'
  pipelineName:
    required: true
    description: 'Pipeline Name'
  accessKeyId:
    required: true
    description: 'AWS Access Key ID'
  secretAccessKey:
    required: true
    description: 'AWS Access Secret Key'
runs:
  using: 'node16'
  main: 'dist/index.js'
