name: 'CodePipeline status'
description: 'Provide the status of CodePipeline'
author: 'Leonardo R.'
inputs:
  milliseconds: # change this
    required: false
    description: 'sample input: miliseconds'
    default: '2000'
runs:
  using: 'node16'
  main: 'dist/index.js'
